### ISSUE TITLE
2 Issues, Unable to login to account. and not showing the libraries when connected through adb. 

### ISSUE THREAD

**Issue by RustyRishii** [theapache64/stackzy#103]
1. Unknown Error 
![image](https://github.com/theapache64/stackzy/assets/63153873/583c80aa-55a9-4c03-bd43-a016670568af)

Also, How does it work? If we login with Google, the Stackzy app pulls an app from the Play Store and tells us its libraries and other details.

2. Couldn't find libraries.
![image](https://github.com/theapache64/stackzy/assets/63153873/4e6c8df8-5b6c-42d0-a779-c53fbc2077cc)

The Fiverr app is installed on my phone, I connected it through the USB. It couldn't find libraries.

**Comment by RustyRishii** [comment]
Also, I'm logging in with my secondary google account.

**Comment by theapache64** [comment]
@RustyRishii the login feature works for me. is your account has 2FA enabled?

Btw, i also tried Fiverr app installed in my phone. Looks like its working 

![Image](https://github.com/theapache64/stackzy/assets/9678279/c420e9e7-c9da-42cc-9ff1-2dd92c6224b9)



Can you try download the latest version and try again?

**Comment by theapache64** [comment]
Closing as there has been no response on the issue for the last few days. Feel free to reopen it if it still persists.

**Comment by RustyRishii** [comment]
Hey @theapache64 Sorry I didn't respond. 

I found a new and simple way to check the libraries of an Android app.

![image](https://github.com/user-attachments/assets/d3f92d92-b0f1-4b38-9c77-e123d222dbb4)

https://play.google.com/store/search?q=libchecker&c=apps
You just have to install this app on your phone. Search the app you are looking for. It'll show all the libraries with links.
