### ISSUE TITLE
Suggestion for improvement in design

### ISSUE THREAD

**Issue by manthan1805** [theapache64/stackzy#31]
At bottom of decompiled library listing page there is sharp cut at bottom of the recycler view you can put gradient so fade at bottom side it will looks better. Here I am attaching your current page screenhot as well suggested design screenshot.

![CURENT SCREEN](https://user-images.githubusercontent.com/58104045/110233511-6bee0300-7f4a-11eb-9461-1b252ac85dba.png)

![SUGGESTION](https://user-images.githubusercontent.com/58104045/110233532-9344d000-7f4a-11eb-8086-c5f3723d709b.png)

**Comment by theapache64** [comment]
@manthan1805 Thanks for the feedback. You can expect this in `v1.0.1`

**Comment by theapache64** [comment]
@manthan1805 Here's how it looks right now. If you think it's more/less, we can work on the gradient height. :) 

![image](https://user-images.githubusercontent.com/9678279/111079215-03d98700-851f-11eb-8e8b-eeb1e861efdc.png)

![image](https://user-images.githubusercontent.com/9678279/111079239-24a1dc80-851f-11eb-8dcc-f844d4ce71f6.png)
