### ISSUE TITLE
Use stackzy on MacOS,  did not analysis any library.

### ISSUE THREAD

**Issue by xuwanjin** [theapache64/stackzy#65]
**Describe the bug**
the build with return: An unexpected error occurred while trying to open file /private/var/****/apk-tool.jar

**To Reproduce**
1. Go to 'ADB, SELECT Nexus 5x, '
2. Click on 'Musically, com.zhiliaoapp.musically'
3. Waiting to build with
4. See error: An unexpected error occurred while trying to open file /private/var/****/apk-tool.jar

**Expected behavior**
list all library of Musically app

**Actual behavior**
A clear and concise description of what actually happened.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Mac mini]
 - Version [11.4 Big Sur]
 - java version: [1.8.0_141]
 - Nexus 5x: [Android 10, Pixel Experience OS]
 - stackzy version: [1.0.5]

**Comment by xuwanjin** [comment]
it seems that i need execute java -jar stackzy***.jar in the terminal, Maybe I have a lot of java version in my MacOS

**Comment by theapache64** [comment]
@xuwanjin can you tell whats the output of `java -version`?
