### ISSUE TITLE
Limitation of the global cache mechanism?

### ISSUE THREAD

**Issue by Arunm619** [theapache64/stackzy#74]
Stackzy uses a gloabl caching mechanism, which works as a centralized caching system. Means, if someone decompiled WhatsApp, the next time you try to find the stack, it won't be decompiled and the result will be served from the cache.

 - What if the decompilation done was done long back, and the new requests with more recent APKs are also served with stale data.

**Comment by theapache64** [comment]
@Arunm619 Good to close?

**Comment by theapache64** [comment]
Closing due to no response. Feel free to reopen
