### ISSUE TITLE
Shows JDK not installed on Windows 11

### ISSUE THREAD

**Issue by vrajdesai78** [theapache64/stackzy#85]
<img width="896" alt="image" src="https://user-images.githubusercontent.com/43074241/148948779-9be100d1-beac-42db-a6a1-7deb3f7a8b96.png">

I have already installed JDK 15 but still it shows me error

**Comment by theapache64** [comment]
@vrajdesai78  Can you enter the command `java -version` in your terminal and paste the output here?

**Comment by vrajdesai78** [comment]
> @vrajdesai78  Can you enter the command `java -version` in your terminal and paste the output here?

It's okay I have cloned the repo and build project instead of directly downloading MSI file.

**Comment by theapache64** [comment]
Okay. Anyway, it looks like a duplicate of #82
