### ISSUE TITLE
How to change DI from dagger to koin

### ISSUE THREAD

**Issue by dpnkrg** [theapache64/stackzy#99]
Hi @theapache64, 

I am just wondering, if we can change the dependency injection tool from dagger to koin. 
Any help or steps are from your end?

**Comment by theapache64** [comment]
Hi @dpnkrg Why do you want to do that? 🤔

**Comment by dpnkrg** [comment]
Hi @theapache64. 
The learning curve for Koin is lesser than Dagger. Also the Koin is fully based on Kotlin and provide simplicity as well in terms of implementation. 
That is the reason for me. :)

**Comment by theapache64** [comment]
I mean, why do you want to implement koin here in Stackzy?

**Comment by dpnkrg** [comment]
Hi @theapache64, 

I am working on a Compose Desktop Application, the core is shared with the Android Application on the front end side.
For Android we are using Koin as a DI. So for the Desktop app I also need to use Koin DI.

This is not for the Stackzy, But I just wanted to know the way of implementation for apps like Stackzy.

**Comment by theapache64** [comment]
> This is not for Stackzy, But I just wanted to know the way of implementation for apps like Stackzy.
@dpnkrg Ohh.. got it. I haven't tried Koin.
